# -*- coding: utf-8 -*-
"""Final_Cryptocurrency_Price_Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pndTvRfbJHo2szBdKYjMY3qPpA-NWjQb

# Cryptocurrency Price Prediction using XGBoost

## Project Overview
This notebook implements a machine learning model to predict Binance Coin prices using XGBoost regression.

## 1. Import Required Libraries
"""

# Data manipulation and analysis
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine learning
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

# Suppress warnings
import warnings
warnings.filterwarnings('ignore')

# Set visualization style
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

"""## 2. Load and Explore Data"""

# Load the historical cryptocurrency data
dataset = pd.read_csv('Binance Coin - Historic data.csv')

# Display basic information
print(f"Dataset Shape: {dataset.shape}")
print(f"\nColumns: {list(dataset.columns)}")
print(f"\nDate Range: {dataset['Date'].iloc[-1]} to {dataset['Date'].iloc[0]}")

# Display first few rows
dataset.head()

"""## 3. Data Preprocessing"""

# Convert volume from string format to numeric
for x in range(dataset['Vol.'].shape[0]):
    val = dataset["Vol."].iloc[x]
    if "M" in val:
        dataset["Vol."].iloc[x] = float(val[:-1]) * 1000000
    elif "K" in val:
        dataset["Vol."].iloc[x] = float(val[:-1]) * 1000

# Convert volume column to numeric type
dataset['Vol.'] = pd.to_numeric(dataset['Vol.'], errors='coerce')

# Convert date column to datetime type
dataset['Date'] = pd.to_datetime(dataset['Date'])

# Sort by date in ascending order
dataset = dataset.sort_values('Date').reset_index(drop=True)

"""## 4. Feature Engineering"""

#  Predict Price change in %
dataset['current_price'] = dataset['Price(in dollars)']
dataset['next_price'] = dataset['Price(in dollars)'].shift(-1)
dataset['Target_pct_change'] = ((dataset['next_price'] - dataset['current_price']) / dataset['current_price']) * 100

# Recent percentage changes
dataset['prev_pct_change_1d'] = dataset['Price(in dollars)'].pct_change(1) * 100
dataset['prev_pct_change_2d'] = dataset['Price(in dollars)'].pct_change(2) * 100
dataset['prev_pct_change_7d'] = dataset['Price(in dollars)'].pct_change(7) * 100

# Measure price fluctuation
dataset['volatility_7d'] = dataset['prev_pct_change_1d'].rolling(window=7).std()
dataset['volatility_14d'] = dataset['prev_pct_change_1d'].rolling(window=14).std()

# High-Low range as percentage (Same Day/Intraday)
dataset['prev_hl_range_pct'] = ((dataset['High'].shift(1) - dataset['Low'].shift(1)) / dataset['Low'].shift(1)) * 100

# Average prices over different time windows
dataset['ma_7'] = dataset['Price(in dollars)'].rolling(window=7).mean()    # 7 day average
dataset['ma_14'] = dataset['Price(in dollars)'].rolling(window=14).mean()  # 14 day average
dataset['ma_30'] = dataset['Price(in dollars)'].rolling(window=30).mean()  # 30 day average

# Price position relative to moving averages (Bullish/Bearish)
dataset['price_to_ma7_ratio'] = (dataset['current_price'] / dataset['ma_7']) * 100
dataset['price_to_ma14_ratio'] = (dataset['current_price'] / dataset['ma_14']) * 100
dataset['price_to_ma30_ratio'] = (dataset['current_price'] / dataset['ma_30']) * 100

# Trading volume changes (high volume confirms price moves)
dataset['volume_change_pct'] = dataset['Vol.'].pct_change(1) * 100

# RSI (Relative Strength Index) - momentum oscillator
# RSI > 70: Overbought (potential sell signal)
# RSI < 30: Oversold (potential buy signal)
delta = dataset['Price(in dollars)'].diff()
gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
rs = gain / loss
dataset['rsi_14'] = 100 - (100 / (1 + rs))

# Temporal patterns
dataset['day_of_week'] = dataset['Date'].dt.dayofweek  # 0=Monday, 6=Sunday
dataset['month'] = dataset['Date'].dt.month            # 1=January, 12=December
dataset['quarter'] = dataset['Date'].dt.quarter        # 1=Q1, 4=Q4

"""## 5. Data Cleaning"""

# Remove rows with NaN values
dataset_clean = dataset.dropna().reset_index(drop=True)

"""## 6. Train-Test Split
Chronological split:
- Training: Earlier 80% of data
- Testing: Later 20% of data
"""

split_idx = int(len(dataset_clean) * 0.8)

train_data = dataset_clean[:split_idx]
test_data = dataset_clean[split_idx:]

print(f"\nTraining Period: {train_data['Date'].iloc[0].strftime('%Y-%m-%d')} to {train_data['Date'].iloc[-1].strftime('%Y-%m-%d')}")
print(f"Testing Period:  {test_data['Date'].iloc[0].strftime('%Y-%m-%d')} to {test_data['Date'].iloc[-1].strftime('%Y-%m-%d')}")
print(f"\nTraining Samples: {len(train_data)} ({len(train_data)/len(dataset_clean)*100:.1f}%)")
print(f"Testing Samples:  {len(test_data)} ({len(test_data)/len(dataset_clean)*100:.1f}%)")
print(f"\nPrice Statistics:")
print(f"  Training - Min: ${train_data['current_price'].min():.2f}, Max: ${train_data['current_price'].max():.2f}, Avg: ${train_data['current_price'].mean():.2f}")
print(f"  Testing  - Min: ${test_data['current_price'].min():.2f}, Max: ${test_data['current_price'].max():.2f}, Avg: ${test_data['current_price'].mean():.2f}")

feature_cols = [
    # Price momentum
    'prev_pct_change_1d', 'prev_pct_change_2d', 'prev_pct_change_7d',
    # Volatility
    'volatility_7d', 'volatility_14d', 'prev_hl_range_pct',
    # Moving average ratios
    'price_to_ma7_ratio', 'price_to_ma14_ratio', 'price_to_ma30_ratio',
    # Volume
    'volume_change_pct',
    # Technical indicators
    'rsi_14',
    # Temporal
    'day_of_week', 'month', 'quarter'
]

# Feature matrices and target vectors
X_train = train_data[feature_cols].values
y_train = train_data['Target_pct_change'].values

X_test = test_data[feature_cols].values
y_test = test_data['Target_pct_change'].values

test_current_prices = test_data['current_price'].values
test_actual_prices = test_data['next_price'].values

"""## 7. Model Training

"""

# Initialize XGBoost Regressor
regressor = XGBRegressor(
    objective='reg:squarederror',
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    min_child_weight=3,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

# Training the model
regressor.fit(
    X_train,
    y_train,
    eval_set=[(X_train, y_train), (X_test, y_test)],
    verbose=True
)

"""## 8. Make Predictions"""

# Predict percentage changes
y_train_pred_pct = regressor.predict(X_train)
y_test_pred_pct = regressor.predict(X_test)

# Convert predicted percentage changes back to dollar prices
test_pred_prices = test_current_prices * (1 + y_test_pred_pct / 100)

"""## 9. Model Evaluation

**Metrics:**
- **R² Score**: Proportion of variance explained (0-1, higher is better)
- **RMSE**: Root Mean Squared Error in dollars (lower is better)
- **MAE**: Mean Absolute Error in dollars (average prediction error)
- **MAPE**: Mean Absolute Percentage Error (average % error)
"""

train_r2_pct = r2_score(y_train, y_train_pred_pct)
test_r2_pct = r2_score(y_test, y_test_pred_pct)

train_mae_pct = mean_absolute_error(y_train, y_train_pred_pct)
test_mae_pct = mean_absolute_error(y_test, y_test_pred_pct)

# Metrics on Dollar Price Predictions
test_r2_dollar = r2_score(test_actual_prices, test_pred_prices)
test_rmse_dollar = np.sqrt(mean_squared_error(test_actual_prices, test_pred_prices))
test_mae_dollar = mean_absolute_error(test_actual_prices, test_pred_prices)
test_mape = np.mean(np.abs((test_actual_prices - test_pred_prices) / test_actual_prices)) * 100

# Display Results
print("="*80)
print("MODEL PERFORMANCE METRICS")
print("="*80)

print("\n📊 PERCENTAGE CHANGE PREDICTIONS:")
print(f"  Training Set:")
print(f"    R² Score:      {train_r2_pct:.4f} ({train_r2_pct*100:.2f}%)")
print(f"    MAE:           {train_mae_pct:.2f}%")
print(f"\n  Testing Set:")
print(f"    R² Score:      {test_r2_pct:.4f} ({test_r2_pct*100:.2f}%)")
print(f"    MAE:           {test_mae_pct:.2f}%")

print("\n💰 DOLLAR PRICE PREDICTIONS (Test Set):")
print(f"  R² Score:        {test_r2_dollar:.4f} ({test_r2_dollar*100:.2f}%)")
print(f"  RMSE:            ${test_rmse_dollar:.2f}")
print(f"  MAE:             ${test_mae_dollar:.2f}")
print(f"  MAPE:            {test_mape:.2f}%")

print("\n💡 INTERPRETATION:")
print(f"  • Model predicts percentage changes with {test_mae_pct:.2f}% average error")
print(f"  • When converted to dollars, average prediction error is ${test_mae_dollar:.2f}")
print(f"  • Model explains {test_r2_dollar*100:.1f}% of future price variation")
print(f"  • On a ${test_current_prices.mean():.2f} average price, error is {test_mape:.1f}%")

print("\n" + "="*80)

"""## 10. Feature Importance Analysis"""

# Extract feature importance scores
feature_importance = pd.DataFrame({
    'Feature': feature_cols,
    'Importance': regressor.feature_importances_
}).sort_values('Importance', ascending=False)

print("\nTop 10 Most Important Features:")
print("="*60)
print(feature_importance.head(10).to_string(index=False))

# Visualize feature importance
plt.figure(figsize=(10, 6))
top_features = feature_importance.head(10)
plt.barh(top_features['Feature'], top_features['Importance'], color='steelblue')
plt.xlabel('Importance Score', fontsize=12)
plt.title('Top 10 Feature Importance', fontsize=14, fontweight='bold')
plt.gca().invert_yaxis()  # Highest importance at top
plt.grid(True, alpha=0.3, axis='x')
plt.tight_layout()
plt.show()

"""## 11. Visualization of Results"""

# Create comprehensive visualization dashboard
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('XGBoost Model - Cryptocurrency Price Prediction', fontsize=16, fontweight='bold', y=1.00)

# ============================================================================
# Plot 1: Time Series - Actual vs Predicted Prices
# ============================================================================
ax1 = axes[0, 0]
ax1.plot(test_data['Date'].values, test_actual_prices,
         label='Actual Price', color='#2E86AB', linewidth=2.5)
ax1.plot(test_data['Date'].values, test_pred_prices,
         label='Predicted Price', color='#E63946', linewidth=2, alpha=0.8, linestyle='--')
ax1.set_title('Actual vs Predicted Prices Over Time', fontsize=12, fontweight='bold', pad=10)
ax1.set_xlabel('Date', fontsize=11)
ax1.set_ylabel('Price (USD)', fontsize=11)
ax1.legend(loc='best', fontsize=10)
ax1.grid(True, alpha=0.3, linestyle='--')
ax1.tick_params(axis='x', rotation=45)

# ============================================================================
# Plot 2: Prediction Errors Distribution
# ============================================================================
ax2 = axes[0, 1]
errors = test_actual_prices - test_pred_prices
ax2.scatter(range(len(errors)), errors, alpha=0.6, color='#A23B72', s=30)
ax2.axhline(y=0, color='#E63946', linestyle='--', linewidth=2)
ax2.fill_between(range(len(errors)), errors, 0, alpha=0.2, color='#A23B72')
ax2.set_title('Prediction Errors (Actual - Predicted)', fontsize=12, fontweight='bold', pad=10)
ax2.set_xlabel('Test Sample Index', fontsize=11)
ax2.set_ylabel('Error (USD)', fontsize=11)
ax2.grid(True, alpha=0.3, linestyle='--')
ax2.text(0.05, 0.95, f'Mean Error: ${errors.mean():.2f}\nStd Dev: ${errors.std():.2f}',
         transform=ax2.transAxes, fontsize=9, verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

# ============================================================================
# Plot 3: Scatter Plot - Predicted vs Actual
# ============================================================================
ax3 = axes[1, 0]
ax3.scatter(test_actual_prices, test_pred_prices, alpha=0.6, color='#06A77D', s=50, edgecolors='black', linewidth=0.5)
# Perfect prediction line
ax3.plot([test_actual_prices.min(), test_actual_prices.max()],
         [test_actual_prices.min(), test_actual_prices.max()],
         'r--', linewidth=2, label='Perfect Prediction')
ax3.set_title('Predicted vs Actual Prices', fontsize=12, fontweight='bold', pad=10)
ax3.set_xlabel('Actual Price (USD)', fontsize=11)
ax3.set_ylabel('Predicted Price (USD)', fontsize=11)
ax3.legend(loc='upper left', fontsize=10)
ax3.grid(True, alpha=0.3, linestyle='--')
ax3.text(0.05, 0.95, f'R² = {test_r2_dollar:.4f}\nMAE = ${test_mae_dollar:.2f}',
         transform=ax3.transAxes, fontsize=9, verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.5))

# ============================================================================
# Plot 4: Percentage Change Predictions
# ============================================================================
ax4 = axes[1, 1]
ax4.scatter(y_test, y_test_pred_pct, alpha=0.6, color='#F18F01', s=50, edgecolors='black', linewidth=0.5)
# Perfect prediction line
ax4.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()],
         'r--', linewidth=2, label='Perfect Prediction')
ax4.axhline(y=0, color='gray', linestyle=':', linewidth=1, alpha=0.5)
ax4.axvline(x=0, color='gray', linestyle=':', linewidth=1, alpha=0.5)
ax4.set_title('Predicted vs Actual Percentage Changes', fontsize=12, fontweight='bold', pad=10)
ax4.set_xlabel('Actual % Change', fontsize=11)
ax4.set_ylabel('Predicted % Change', fontsize=11)
ax4.legend(loc='upper left', fontsize=10)
ax4.grid(True, alpha=0.3, linestyle='--')
ax4.text(0.05, 0.95, f'R² = {test_r2_pct:.4f}\nMAE = {test_mae_pct:.2f}%',
         transform=ax4.transAxes, fontsize=9, verticalalignment='top',
         bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.5))

plt.tight_layout()
plt.show()

"""## 12. Sample Predictions

Examine recent predictions in detail to understand model performance.
"""

# Create detailed comparison dataframe
comparison = pd.DataFrame({
    'Date': test_data['Date'].tail(20).values,
    'Today_Price': test_current_prices[-20:],
    'Actual_Tomorrow': test_actual_prices[-20:],
    'Predicted_Tomorrow': test_pred_prices[-20:],
    'Error_$': test_actual_prices[-20:] - test_pred_prices[-20:],
    'Error_%': ((test_actual_prices[-20:] - test_pred_prices[-20:]) / test_actual_prices[-20:] * 100),
    'Predicted_%_Change': y_test_pred_pct[-20:],
    'Actual_%_Change': y_test[-20:]
})

# Format for better display
comparison['Today_Price'] = comparison['Today_Price'].apply(lambda x: f'${x:.2f}')
comparison['Actual_Tomorrow'] = comparison['Actual_Tomorrow'].apply(lambda x: f'${x:.2f}')
comparison['Predicted_Tomorrow'] = comparison['Predicted_Tomorrow'].apply(lambda x: f'${x:.2f}')
comparison['Error_$'] = comparison['Error_$'].apply(lambda x: f'${x:.2f}')
comparison['Error_%'] = comparison['Error_%'].apply(lambda x: f'{x:.2f}%')
comparison['Predicted_%_Change'] = comparison['Predicted_%_Change'].apply(lambda x: f'{x:+.2f}%')
comparison['Actual_%_Change'] = comparison['Actual_%_Change'].apply(lambda x: f'{x:+.2f}%')

print("\n" + "="*120)
print("SAMPLE PREDICTIONS - Last 20 Test Days")
print("="*120)
print(comparison.to_string(index=False))

"""## 13. Model Usage


"""

import joblib

# Save the trained model
model_filename = 'xgboost_binance_predictor.pkl'
joblib.dump(regressor, model_filename)

print("=" * 80)
print("MODEL SAVED")
print("=" * 80)
print(f"\n✓ Model saved as: '{model_filename}'")
print(f"✓ File location: Current working directory")
print(f"\nTo load the model later:")
print(f"  loaded_model = joblib.load('{model_filename}')")
print(f"  prediction = loaded_model.predict(features)")
print("=" * 80)

def calculate_prediction_features(price_df):
    """
    Calculate all 14 features from recent price data for making new predictions.

    Parameters:
    -----------
    price_df : pandas.DataFrame
        DataFrame with columns: Date, Price, High, Low, Volume
        Minimum 35 days of data required

    Returns:
    --------
    features : list
        List of 14 features ready for model prediction (in exact order)
    current_price : float
        Today's closing price
    df : pandas.DataFrame
        DataFrame with all calculated features (for inspection)
    """
    df = price_df.copy()

    # Ensure proper date format and sorting
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date').reset_index(drop=True)

    # Rename to match
    if 'Price' not in df.columns and 'Close' in df.columns:
        df['Price'] = df['Close']

    # Calculate all derived features

    # Features 1-3: Price momentum (percentage changes)
    df['pct_change_1d'] = df['Price'].pct_change(1) * 100
    df['pct_change_2d'] = df['Price'].pct_change(2) * 100
    df['pct_change_7d'] = df['Price'].pct_change(7) * 100

    # Features 4-6: Volatility measures
    df['volatility_7d'] = df['pct_change_1d'].rolling(window=7).std()
    df['volatility_14d'] = df['pct_change_1d'].rolling(window=14).std()
    df['hl_range_pct'] = ((df['High'] - df['Low']) / df['Low']) * 100

    # Calculate moving averages for features 7-9
    df['ma_7'] = df['Price'].rolling(window=7).mean()
    df['ma_14'] = df['Price'].rolling(window=14).mean()
    df['ma_30'] = df['Price'].rolling(window=30).mean()

    # Feature 10: Volume change
    df['volume_change_pct'] = df['Volume'].pct_change(1) * 100

    # Feature 11: RSI calculation
    delta = df['Price'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    rs = gain / loss
    df['rsi_14'] = 100 - (100 / (1 + rs))

    # Extract today's values (last row, index -1)
    current_price = df['Price'].iloc[-1]
    today = df['Date'].iloc[-1]


    features = [
        df['pct_change_1d'].iloc[-1],
        df['pct_change_2d'].iloc[-1],
        df['pct_change_7d'].iloc[-1],
        df['volatility_7d'].iloc[-1],
        df['volatility_14d'].iloc[-1],
        df['hl_range_pct'].iloc[-2],
        (current_price / df['ma_7'].iloc[-1]) * 100,
        (current_price / df['ma_14'].iloc[-1]) * 100,
        (current_price / df['ma_30'].iloc[-1]) * 100,
        df['volume_change_pct'].iloc[-1],
        df['rsi_14'].iloc[-1],
        today.dayofweek,
        today.month,
        (today.month - 1) // 3 + 1
    ]

    return features, current_price, df

def predict_next_day(recent_price_data, trained_model):
    """
    Complete pipeline to predict tomorrow's price.

    Parameters:
    -----------
    recent_price_data : pandas.DataFrame
        Recent price data with columns: Date, Price/Close, High, Low, Volume
        Minimum 35 days required
    trained_model : XGBRegressor
        Your trained XGBoost model

    Returns:
    --------
    dict : Dictionary containing:
        - current_price: Today's closing price
        - predicted_price: Tomorrow's predicted price
        - predicted_change_pct: Predicted percentage change
        - predicted_change_usd: Predicted dollar change
        - signal: Trading signal (BUY/SELL/HOLD)
        - confidence: Signal confidence (HIGH/MEDIUM/LOW)
        - features: Feature vector used (for inspection)
        - rsi: RSI value
        - trend_7d: 7-day price trend
    """
    # Calculate features
    features, current_price, df = calculate_prediction_features(recent_price_data)

    # Make prediction
    features_array = np.array(features).reshape(1, -1)
    predicted_pct_change = trained_model.predict(features_array)[0]

    # Calculate predicted price
    predicted_price = current_price * (1 + predicted_pct_change / 100)
    price_change_usd = predicted_price - current_price

    # Generate trading signal
    if predicted_pct_change > 2.0:
        signal = "BUY"
        confidence = "HIGH" if predicted_pct_change > 3.0 else "MEDIUM"
    elif predicted_pct_change < -2.0:
        signal = "SELL"
        confidence = "HIGH" if predicted_pct_change < -3.0 else "MEDIUM"
    else:
        signal = "HOLD"
        confidence = "LOW"

    # Return results
    return {
        'current_price': current_price,
        'predicted_price': predicted_price,
        'predicted_change_pct': predicted_pct_change,
        'predicted_change_usd': price_change_usd,
        'signal': signal,
        'confidence': confidence,
        'features': features,
        'rsi': features[10],
        'trend_7d': features[2]
    }

print("\nSCENARIO: March 6, 2024 - BNB is currently $425.00")
print("QUESTION: Should I invest $5,000 in BNB right now?\n")


# Create realistic 35-day price history
demo_prices = pd.DataFrame({
    'Date': pd.date_range(end='2024-03-06', periods=35),
    'Price': [
        380, 385, 388, 392, 390, 395, 402, 405, 408, 412,
        410, 415, 418, 416, 420, 422, 425, 428, 426, 430,
        432, 435, 433, 437, 440, 438, 442, 445, 443, 446,
        448, 446, 443, 441, 425  # Today: dropped to $425
    ],
    'High': [
        385, 390, 393, 397, 395, 400, 407, 410, 414, 418,
        415, 420, 423, 422, 425, 428, 430, 433, 432, 435,
        438, 441, 438, 443, 446, 444, 448, 451, 448, 452,
        454, 451, 449, 446, 430
    ],
    'Low': [
        375, 380, 383, 387, 385, 390, 397, 400, 404, 408,
        405, 410, 413, 412, 415, 418, 420, 423, 422, 425,
        428, 431, 428, 433, 436, 434, 438, 441, 438, 442,
        444, 441, 439, 436, 420
    ],
    'Volume': [
        3800000, 4100000, 3950000, 4200000, 3900000,
        4300000, 4600000, 4450000, 4700000, 4850000,
        4600000, 4900000, 5100000, 4950000, 5200000,
        5350000, 5500000, 5650000, 5400000, 5800000,
        5950000, 6100000, 5850000, 6300000, 6450000,
        6200000, 6500000, 6750000, 6450000, 6900000,
        7050000, 6800000, 6550000, 6300000, 8500000
    ]
})

print("\nSTEP 1: Analyzing Last 35 Days")
print(f"Price Range: ${demo_prices['Price'].min():.2f} - ${demo_prices['Price'].max():.2f}")
print(f"Current: ${demo_prices['Price'].iloc[-1]:.2f}")

# Calculate features and predict
result = predict_next_day(demo_prices, regressor)

print("\nSTEP 2: AI Prediction")
print(f"Predicted Tomorrow: ${result['predicted_price']:.2f}")
print(f"Expected Change: ${result['predicted_change_usd']:+.2f} ({result['predicted_change_pct']:+.2f}%)")

print("\nSTEP 3: Trading Signal")
if result['signal'] == 'BUY':
    print(f"{result['signal']} - Expecting price increase")
elif result['signal'] == 'SELL':
    print(f"{result['signal']} - Expecting price decrease")
else:
    print(f"{result['signal']} - Small change, not worth trading")
print(f"Confidence: {result['confidence']}")

print("\nSTEP 4: Investment Analysis ($5,000)")
investment = 5000
coins = investment / result['current_price']
tomorrow_value = coins * result['predicted_price']
profit = tomorrow_value - investment
roi = (profit / investment) * 100

print(f"Current Investment:  ${investment:,.2f}")
print(f"BNB Coins:          {coins:.4f}")
print(f"Tomorrow's Value:   ${tomorrow_value:,.2f}")
print(f"Expected Profit:    ${profit:+,.2f}")
print(f"Expected ROI:       {roi:+.2f}%")


print("RECOMMENDATION:", end=" ")
if result['signal'] == 'BUY' and result['confidence'] in ['HIGH', 'MEDIUM']:
    print(f"Consider buying - {result['signal']} signal with {result['confidence']} confidence")
elif result['signal'] == 'SELL':
    print(f"Consider selling or waiting - Downward trend expected")
else:
    print(f"Hold or wait - Small movement expected")